.\" © 2013, 2015-2016 Benjamin Barenblat
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License"); you may not
.\" use this file except in compliance with the License.  You may obtain a copy
.\" of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS, W.TPOUT
.\" WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
.\" License for the specific language governing permissions and limitations
.\" under the License.
.pc
.TH bvd 1 "2016-04-01" "Git snapshot 97628c" Boogie
.SH NAME
bvd \- Boogie Verification Debugger
.SH SYNOPSIS
.B bvd
.SH DESCRIPTION
.B bvd
is an interactive verification condition debugger for for Microsoft Research's Boogie programming language.
.SH OPTIONS
.B bvd
is a graphical program and accepts no options on the command line.
.SH COPYRIGHT
Boogie is copyright \(co 2003-2015 Microsoft Corporation and licensed under the Microsoft Public License <https://msdn.microsoft.com/en-us/library/ff647676.aspx>.

This manual page is copyright \(co 2013, 2015-2016 Benjamin Barenblat and licensed under the Apache License, Version 2.0.
